server {

    listen 80;

    server_name
        api.flowpay.com
        app.flowpay.com;

    client_max_body_size 50M;

    # =========================
    # FRONTEND
    # =========================

    location / {

        proxy_pass
            http://frontend:3000;

        proxy_http_version 1.1;

        proxy_set_header
            Upgrade $http_upgrade;

        proxy_set_header
            Connection "upgrade";

        proxy_set_header
            Host $host;

        proxy_cache_bypass
            $http_upgrade;
    }

    # =========================
    # BACKEND API
    # =========================

    location /api {

        proxy_pass
            http://backend:5000;

        proxy_http_version 1.1;

        proxy_set_header
            Upgrade $http_upgrade;

        proxy_set_header
            Connection "upgrade";

        proxy_set_header
            Host $host;

        proxy_cache_bypass
            $http_upgrade;
    }

    # =========================
    # SOCKET.IO
    # =========================

    location /socket.io/ {

        proxy_pass
            http://backend:5000/socket.io/;

        proxy_http_version 1.1;

        proxy_set_header
            Upgrade $http_upgrade;

        proxy_set_header
            Connection "Upgrade";

        proxy_set_header
            Host $host;

        proxy_cache_bypass
            $http_upgrade;
    }
}